apiVersion: v1
kind: Service
metadata:
  name: cafe-wallarm
  labels:
    run: cafe-wallarm
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: cafe-wallarm